### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#16]
this is something that I like because my posts/notes are longer than what you write, I think.
I use the files more like a documentation that is split in different posts/notes.
Because the posts are longer, I loose track over the file, even when I use the tags. So right now, in my local fork, I use the `--toc` option for pandoc so I see the titles of the posts and can easily jump to the one I want. It's no that pretty and I don't know, how to put it under the title, but it works for me

![no_toc](https://cloud.githubusercontent.com/assets/6723020/4790605/3aafdc86-5dd3-11e4-8e7b-ac7255af6daf.png)

it works with tags of course:
![no_toc2](https://cloud.githubusercontent.com/assets/6723020/4790624/5ee3964c-5dd3-11e4-81f7-27199ae0152c.png)

----

edit:
What do you think of a config (-file) for setting these kind of things? Maybe the show/hide empty folders option could go there, too. Another way would be a plugin-system, but that's kind of a stretch.

**Comment by egolus** [comment]
I added a menu entry for this:
egolus/Noteorganiser@cace063144511b986c7060160d11c9e94014df1a

what do you think?

another thing: what would you write as a test for these menu entries? 'click' the menu entry and assert the change of the config-entry?

**Comment by baudren** [comment]
@egolus, can I try to create a PR from this? There will be some rebasing to do, but I can do that. Are you using it still, do you consider the feature implemented?

**Comment by egolus** [comment]
I can do it. I allready rebased it in my local tree some time ago, because I still use it. I agree that it's not really beautiful. One way to make it a bit nicer would be to create a Template for pandoc, but I don't know how much work this would be

**Comment by baudren** [comment]
Since it is optional anyway, the good looks are not so important right now. You could open a PR as is, then, and let's integrate it in devel

**Comment by egolus** [comment]
I created the PR: #41

**Comment by baudren** [comment]
PR #41 is now merged!
