### ISSUE TITLE
Feedback on error generating the preview

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#18]
I think, it would be nice, if the user gets a feedback as a message box, when you fail to generate the preview. At least for me right now, it's the most common problem.
I see the error in the command window, but when you start python without command window, you don't get any feedback and your program just doesn't react to the click on `preview`

I'm talking about these errors:

~~~
Traceback (most recent call last):
  File "noteorganiser\NoteOrganiser.py", line 145, in previewNotebook
    self.preview.loadNotebook(notebook)
  File "c:\_programmierung\noteorganizer\fork\noteorganiser\noteorganiser\frames.py", line 391, in loadNotebook
    os.path.join(self.info.level, notebook), tags)
  File "c:\_programmierung\noteorganizer\fork\noteorganiser\noteorganiser\frames.py", line 416, in convert
    path, input_tags=tags)
  File "c:\_programmierung\noteorganizer\fork\noteorganiser\noteorganiser\text_processing.py", line 236, in from_notes_to_markdown
    title, posts = extract_title_and_posts_from_text(text)
  File "c:\_programmierung\noteorganizer\fork\noteorganiser\noteorganiser\text_processing.py", line 211, in extract_title_and_posts_from_text
    posts[index] = normalize_post(post)
  File "c:\_programmierung\noteorganizer\fork\noteorganiser\noteorganiser\text_processing.py", line 146, in normalize_post
    dashline_index = post.index(dashes[0])
IndexError: list index out of range
~~~

in this case, the problem was generated by this text:

~~~
-	--  nicht moeglich
~~~

it's a list-item with two dashes in the listitem-text but it looks like your code ignores the whitespace and sees three dashes. When i change it to

~~~
-	-\-  nicht moeglich
~~~

it works again. 
It's no problem, but I run into these problems from time to time and it would be nice to get a feedback, when i click on `preview`

**Comment by baudren** [comment]
I agree something is needed, instead of the current silent failure. Would a popup, with the error message, work? I think this is the most logical solution for the interface.

**Comment by egolus** [comment]
Yes, I think, a popup would be the logical thing. The question is what to put in as message. Just the error text? Can a user interpret that?

**Comment by baudren** [comment]
Well, there are two cases.

Either it is a foreseen error (for instance, many possible errors have been taken into account in [text_processing.py](noteorganiser/text_processing.py)), and display a relatively clear error message at the end of the trace.

Or it is an unexpected error, in which case the stack trace is still a better information than none, and it will eventually be caught and processed to give a better error.

So: stacktrace! That might be scary for a few people, but it is cleaner than a silent failure with no indication.

**Comment by egolus** [comment]
Yes, I totally agree

Am 22. April 2015 13:58:31 MESZ, schrieb Benjamin Audren <notifications@github.com>:

**Comment by baudren** [comment]
There you go. I realised, while improving error messages, that there are some things still going wrong, like if you mess up a little bit your underlining of a post title, it is ignored completely:

~~~
...
A very nice post
--------_-----------
# mistakes, can, happen
...
~~~

But maybe this belongs to a new issue

**Comment by egolus** [comment]
ok, i'll try to test this

**Comment by egolus** [comment]
@baudren some errors are handled nicely by a popup

I found one that isn't handled yet:
If you have an empty line where the tags should be

~~~
test
----

*25/04/2015*

this is the post
~~~

~~~
Traceback (most recent call last):
  File "C:\_Programmierung\noteorganiser\fork\NoteOrganiser\noteorganiser\NoteOrganiser.py", line 190, in previewNotebook
    if self.preview.loadNotebook(notebook):
  File "c:\_programmierung\noteorganiser\fork\noteorganiser\noteorganiser\frames.py", line 410, in loadNotebook
    os.path.join(self.info.level, notebook), tags)
  File "c:\_programmierung\noteorganiser\fork\noteorganiser\noteorganiser\frames.py", line 445, in convert
    path, input_tags=tags)
  File "c:\_programmierung\noteorganiser\fork\noteorganiser\noteorganiser\text_processing.py", line 249, in from_notes_to_markdown
    tags, post = extract_tags_from_post(post)
  File "c:\_programmierung\noteorganiser\fork\noteorganiser\noteorganiser\text_processing.py", line 95, in extract_tags_from_post
    return tags, post[:2]+post[3:]
UnboundLocalError: local variable 'tags' referenced before assignment
~~~

**Comment by baudren** [comment]
Indeed. Now it is done, but the next step is to make these traceback more verbose. I reopen the issue to address this, because currently, it is more like a workaround than anything.

**Comment by baudren** [comment]
With 8f0c24d and  ef83c07, I caught properly the two possible errors mentionned in this thread. One was actually due to the function `is_valid_post` which was not completely working as expected. I replaced a bunch of `find` to their more robust regular expressions counterparts. Overall, error messages should be less painful now.

Feel free to close the issue if you think it is ok now.

**Comment by egolus** [comment]
The changes look good.
I'll test a bit tomorrow and close it then. 

Just out of interrest, wouldn't it be easier to actually test for a date instead of the regex? There should be a method, right? something like `toDate(string) != null`

**Comment by baudren** [comment]
@egolus, as far as I know, the `datetime` module allows you to parse a date in a predefined format. It can not interpret any valid date string into a date, because of the different possible conventions.

Of course, in the situation `23/01/2015`, there is no possible concern on which entry is the day/month/year, but for many other cases, you have to impose a format for the date, essentially boiling down to a regex (which was faulty previously, by the way :disappointed: ). So I think that I can keep my painfully constructed regex.

What I could do, however, is specify the expected date format somewhere in the error message!

**Comment by egolus** [comment]
I've found some cases that problably don't behave as intended:

you generate a tag ' ' (empty string) if there is no text in the tag-line:

~~~
test
--------
#


*25/04/2015*

this is the post
~~~

____

you generate an empty post, if there is no empty line after the tag-line:

~~~
test
--------
#tag
*25/04/2015*

this is the post
~~~

**Comment by egolus** [comment]
Can we close this? All issues I found are fixed, right?

**Comment by baudren** [comment]
Yes! The releqse is done, by the way. Onwards to 0.3!
