### ISSUE TITLE
Click on 'X' of the MainWindow doesn't call cleanClose

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#22]
the function gets called, when the window is closed by the menu-entry `Exit application` or the Hotkey `Ctrl+Q` but not by the `X` Button on the top-right of the window

I didn't even know that you save the window position until I found the call to `QtCore.QSettings` in your code, because I allways closed the window by clicking the `X`

**Comment by baudren** [comment]
Indeed, the `closeEvent` function was not overwritten. Fixed now!
