### ISSUE TITLE
[windows] double newline in codeblocks

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#23]
This looks like a problem with pypandoc or pandoc on windows.

pandoc on windows generates lineendings as `\r\n` (normal windows line endings)
but when the file is saved as html, this produces two newlines so I get codeblocks like this:

![codeblock_doublenewline](https://cloud.githubusercontent.com/assets/6723020/5902487/2b7ddf84-a57b-11e4-9480-0a37d3c768b1.png)

I didn't catch this as an issue first because I thought, it was just a css-issue. Also, I haven't seen any differences in the output but in the codeblocks.

my first workaround is to just replace `\r\n` with `\n` in `frames.py` (function `convert`)

**Comment by baudren** [comment]
That's funny. I did a checkout of the code for the first time on a windows machine today, and notice this exact problem!

Could you confirm that it works?

**Comment by egolus** [comment]
Sorry, it doesn't.

You are working on the wrong string. it's the output from pandoc you want to work on:
https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/frames.py#L435-L437

so:
~~~
html = html.replace('\r\n', '\n')
~~~

**Comment by baudren** [comment]
Ah, yes, I am stupid. Writing it to the file applies the windows convention again...

**Comment by egolus** [comment]
@baudren 
Yes, now it works
