### ISSUE TITLE
dashlines should only be lines with ONLY dashes

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#25]
right now, every line with two or more dashes in a row is a dashline, so I can't write lines like this:

~~~
- Arguments: `--servername VimStudio --remote-silent +"call cursor($(CurLine),$(CurCol))" "$(ItemFileName)$(ItemExt)"`
~~~

normally, I would escape this with a backslash in the middle ( `-\-` ) but in a code-block this isn't possible

I think, you have to check for lines that have only dashes

(`text_processing.py`, line 167 : `def extract_title_and_posts_from_text(text)` )

**Comment by baudren** [comment]
Yup, good catch, thanks!

**Comment by egolus** [comment]
@baudren: looks good, thanks :)
