### ISSUE TITLE
Fixing Travis Build

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#26]
I noticed recently that the [travis build](https://travis-ci.org/baudren/NoteOrganiser/builds) was failing, since Number 72 (this seemed to be only in python3, with pypandoc), but most importantly, since Number 77, the pyside installation times-out.

When checking on my machine, it is true that `pip install pyside` takes a pretty long time, so it seems reasonnable that with the new time-out limit (10 mins), it fails. I tried adding a `travis_wait pip install pyside`, to increase the time to 20 mins, but it still fails.

I tried to follow some of the advice [on this stackoverflow post](http://stackoverflow.com/questions/24489588/how-can-i-install-pyside-on-travis), but did not find a solution. If anyone had the time/knowledge to look into it, I would be grateful.

**Comment by egolus** [comment]
It looks like somebody is doing something ...

I signed up for travis and it started checking my branches and the results differ from yours:

### current devel
yours: [click](https://travis-ci.org/baudren/NoteOrganiser/jobs/62353448)
mine: [click](https://travis-ci.org/egolus/NoteOrganiser/jobs/62635683)

**Comment by egolus** [comment]
**Progress:**
I looked at the stackoverflow post again and added the wheel by Will Parkin to `.travis.yml` (hosted on his github-space)
here is the result for 2.7: [click](https://travis-ci.org/egolus/NoteOrganiser/jobs/62647020)

**Comment by egolus** [comment]
can we close this issue?

**Comment by baudren** [comment]
Yes! I don't understand why it was not done automatically, since I merged it from Github.. weird. Thanks again
