### ISSUE TITLE
application Icon

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#31]
Over time the standard application icon gets really annoying. 
There should be a possibility to set a custon icon in QT, right?

**Comment by baudren** [comment]
[Yes](http://doc.qt.io/qt-4.8/appicon.html). A question remains before doing it: I think it would be much better to redo the icons in `.svg` format, to give them a crisper look. And the [standing icon](https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/assets/notebook-128.png), if better done, could be the application icon, no?

I like to keep in mind, also, the Google [guidelines for icons](http://www.google.ch/design/spec/style/icons.html#icons-product-icons). The whole thing is worth a read, in my opinion.

That's a [bunch of icons](http://google.github.io/material-design-icons/) that are more suited to inside the application (could be nice to improve the user interface). They are very flat (which is indeed one of the guidelines), but this is ok for an in-app icon, not so much for a logo...

Also, do you have a good tool to draw svg?

**Comment by egolus** [comment]
OK, as I thought, this is for the window. For the taskbar or whereever the OS displays the app, you need a OS-dependent solution.

I haven't worked with svg files, but my icons and vector graphics I created with inkskape. If I wanted to create a windows `.ico` file, I also needed GIMP

**Comment by baudren** [comment]
It is a pity that there is no paltform-independent way of asking `Qt` to put an application icon...

I plan to do a mock-up (traditional ink and paper) of a new version in the coming weeks, that would respect the Google guidelines mentioned. Feel free to do another one! Then we could try and Inkscape it.

**Comment by egolus** [comment]
I've created a pull request: #32

**Comment by baudren** [comment]
The PR is now merged
