### ISSUE TITLE
Button `Refresh` in Preview

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#34]
Now that we can edit the notebook in an external editor, we shouldn't have to go back to the editor and click `preview` there to refresh the preview

**Comment by egolus** [comment]
we can use [the new `reload` function](https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/frames.py#L524)

**Comment by baudren** [comment]
Should we add a button somewhere to implement this behaviour? In the same way that there are buttons on the editor?

**Comment by egolus** [comment]
A button somewhere was my main idea. An auto-refresh could be nice but we have to check the overhead. It has to run pandoc everytime. That's at least more than just reloading the file. But it should be ok..

**Comment by baudren** [comment]
done in #50
