### ISSUE TITLE
Add a search field in editor

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#39]
I think it would be nice to have a way to locate a note in the markdown file.

I often have a note in the html file and want to change something so I have to look through the markdown file in the editor where I can't filter by tags or search for the note-title

an easy way would be a search field that sets the cursor in the editor. But maybe we can think of other ways to filter for tags or to edit single notes, maybe in a popup like the one for new notes ..

**Comment by baudren** [comment]
Agreed. The text editor could use a lot of work. One item would be to have a simple search command, which would highlight results.

**Comment by baudren** [comment]
What do you think about closing it? In terms of #68, this editor could disappear completely, so putting effort into it seems a bit of a waste of time.

**Comment by baudren** [comment]
Ok, let's put this on hold since the editor will disappear.
