### ISSUE TITLE
Add a tag selector when creating a new entry

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#42]
When adding a new entry in an already crowded file, it could be nice to change the tag input line so that it could display a dropdown menu with the list of tags in the file, that you could toggle. It would then proceed into writing the tags in the tag line.

Or we could even go further, and rethink the way the tags are added. Since the goal is to not bother too much with syntax, the fact that it should be comma separated could also be hidden - all there would be are simply tags (labels). If we are not doing this, I was thinking that we could add a syntax checker inside the `New Entry` form, to check that the tag line is valid (and while we are at it, that the title and body are not missing either).

**Comment by egolus** [comment]
You are checking for empty fields, if I recall correctly, so the existence of the title and the body is checked allready. But the rest sounds good. If you want to write it by hand, just write into the editor and if you don't want to bother with syntax, the `New Entry` form helps you as far as possible ..

**Comment by egolus** [comment]
done in #63
