### ISSUE TITLE
Choose main folder to store notebooks

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#45]
By default, now, the home folder is picked, and a `.noteorganiser` folder is created. This then hosts the notebooks.

It would be best to have at launch a popup if the main folder is not set, to select its location. This would allow for choosing a cloud-synced folder, for instance. I was thinking of simply using a standard browsing widget for this.

I am working on a PR right now.

**Comment by egolus** [comment]
yes, a browsing widget at the first start would be nice. Probably you could put this in the menu, too, so the user can change the folder later.

**Comment by baudren** [comment]
done in #53
