### ISSUE TITLE
New entry in contextmenu: preview

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#46]
I think, it would be nice if you were able to just right click on a notebook in the library and select `Preview` to jump right into the preview.

Often you just want to look something up and don't need the editor.

**Comment by baudren** [comment]
Yup, totally agree on this one. Feel free to give it a go - I though it was already part of the roadmap, and I was definitely having this in mind for a long time.

**Comment by baudren** [comment]
Done, with the merging of #47
