### ISSUE TITLE
bootstrap css

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#54]
the new branch `bootstrap` tries to improve the css display, by using the bootstrap [blog](http://getbootstrap.com/examples/blog/#) syntax.
- [x] ~~Fix font display (looks pixelled on my machine)~~ (was there before bootstrap)
- [x] Customize the theme, colors, etc

Now the date are in, in a crude fashion, there is still #35 to think about.

**Comment by baudren** [comment]
Ok, what do you think, should we pull this in `devel`? How does it look for you? Did I miss anything?

**Comment by egolus** [comment]
The TOC doesn't work

**Comment by baudren** [comment]
right - had totally forgot that (it was in the Gitter discussion, maybe). The problem was that markdown text in between html tags (as I use to output bootstrap valid html) is not recognised by the `toc` option of pandoc.

**Comment by egolus** [comment]
I see, the temp-markdown files look interesting

**Comment by baudren** [comment]
Well, [there](https://github.com/jgm/pandoc/issues/997#issuecomment-31503690) is the explanation for the behaviour. I used jgm second recommendation - using `article` instead of `div`, and it works..

That was easy!

**Comment by egolus** [comment]
nice, this looks good. I'll have to change some things in my notebooks, but that is expected.
I don't see any other problem
