### ISSUE TITLE
Adding right click on library to create Notebook/Folder

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#61]
Much like on a regular file explorer, right click in an empty spot usually brings up a menu with the possibility to create a new item. Would be nice to have there.

**Comment by egolus** [comment]
a07c389 adds a context menu to the Library (right click into the empty space)

**Comment by baudren** [comment]
Well, that wraps it up, thanks :+1: Can you open a PR so that we merge that straight away?

**Comment by egolus** [comment]
what I don't like right now is, that I use objects that are declared somewhere else. If you remove `initToolBar`, `initContextMenu` doesn't work any more. I feel like the creation of the actions should be in `Library` itself. but then the two functions barely do anything any more.

(If you think, it's all right how it is, feel free to merge it)

**Comment by baudren** [comment]
I am fine with it, I think. The actions being the same, it makes sense to reuse them. If we believe it would be cleaner to extract them from the `initToolBar` into a `initAction`, we can always do it at a later time. Thanks for the work, again!
