### ISSUE TITLE
We're poluting directories with `log` files

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#78]
now that I have the python-directory in my `$path`, I start noteorganiser from anywhere I just got a shell open. The problem is, that noteorganiser creates a `log`-file in the current working dir. So I have `log` files in at least 5 different places.
And for a normal user `log` maybe is not the best filename to connect it to noteorganiser

**Comment by baudren** [comment]
True that! Let's change it to be placed inside `.noteorganiser`, no? It can then stay called as `log`. Should we keep the behaviour that it is erased at each start-up? Since it is only for debugging, that still makes sense, right?

**Comment by egolus** [comment]
yes, that sounds good. I actually haven't realized that it's erased at each start-up

**Comment by baudren** [comment]
Solved in #79
