### ISSUE TITLE
minimal Width of the window is set because auf the number of Notebooks and the window is too wide

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#9]
is this just windows?

- the library shows all notebooks from left to right, they don't wrap to a second line, when there are too many notebooks
- in the second line, the folders are shown
- the minimal width of the window is set so all items are shown.

The problem is, allready when there are 4 notebooks in a folder, the width of the window is bigger than half of my monitor, so i can't see two windows side by side

can you change the minimal width of the window to an arbitrary, smaller number and make the library scrolling or wrapping the shelves?

**Comment by egolus** [comment]
remaining Problems:
- slow update when resizing the library on Windows
- the shelves set the minimum size for the window, so when you resize with another tab active, you can't go under this minimum size
    - While the `Library` is active, this minimum size get's updated and the items get rearranged according to the width

my PR #38 should fix these two problems

**Comment by baudren** [comment]
Yep it did, now it is in devel, and we could release version 0.2! I will do it tomorrow evening, if no other problem pops up. Thanks again
