### ISSUE TITLE
Button/Function to insert a picture

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#92]
in general we sometimes want to have a picture in the rendered html, for example a screenshot

to achieve this, we need some steps:
- we need to take a screenshot
- maybe we want to crop it and add some markers
- we need to save the file to disk
- we need to insert the filepath inside some markup in the notebook at the cursorposition

as a simple approach we could just implement the last step and do the others outside of noteorganiser

**Comment by baudren** [comment]
I could see this as a first, simple step:
- add a "insert picture" line in right-click on the text editor
- and an icon on the toolbar
- both would open a simple two field dialog: file-browser box and caption name. This would insert the picture with proper markdown tags inside the document, at the cursor's

Once this is in, we could try to detect a drag-and-drop of a picture on top of the text area, and open the same dialog with pre-filled path?

**Comment by egolus** [comment]
done in #95
